on:
  push:
    branches:
      - staging
      - trying

name: bors

jobs:
  bors:
    name: bors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target wasm32-unknown-unknown
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: doc
      # - uses: saltbo/uptoc@master
      #   with:
      #     driver: oss
      #     region: cn-shenzhen
      #     bucket: curdata-rustdoc
      #     dist: target/doc/marrow
