on:
  push:
    branches:
      - staging
      - trying

name: bors

jobs:
  bors:
    name: bors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
      - uses: actions/setup-node@v2
        with: 
          node-version: '15'
      - run: make build
      - run: make test
